apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: amalliar/grafana:latest
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: grafana-secret
      securityContext:
        fsGroup: 472

