apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: grafana-app
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  loadBalancerIP: 192.168.49.3
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana
