apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-app
spec:
  selector:
    app: mysql-app
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
