apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-map
  labels:
    app: telegraf-app
data:
  telegraf.conf: |+
    [agent]
      hostname = "$HOSTNAME"
    [[outputs.influxdb]]
      urls = ["http://$INFLUXDB_HOST:8086/"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
      retention_policy = ""
      write_consistency = "any"
      timeout = "5s"
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      container_name_include = []
      timeout = "5s"
      perdevice = true
      gather_services = true
      total = true
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = true
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.swap]]
    [[inputs.processes]]
    [[inputs.system]]
