apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress-app
  type: LoadBalancer
  loadBalancerIP: 192.168.49.3
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress
